version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    command: ["--auth"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    hostname: rabbit-host
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres
    container_name: my-postgres-banking
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    entrypoint: >
      /bin/sh -c "
      echo 'Adding connection to PostgreSQL...';
      /entrypoint.sh;
      psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB};
      "

volumes:
  pgdata:
  pgadmin-data:
