version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_URI=mongodb://=${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/mydatabase?authSource=admin
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

volumes:
  mongo_data: