version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    command: ["--auth"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    hostname: rabbit-host
    ports:
      - "5672:5672"     # порт для AMQP
      - "15672:15672"   # порт для web-интерфейса управления
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres
    container_name: my-postgres-banking
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
